In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
X = df.drop('species', axis=1)
y = df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=25)

In [ ]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=25)

In [ ]:
model_knn.score(X_test, y_test)

1.0

In [ ]:
model_svm = SVC(C = 30,kernel='rbf',gamma='auto')
model_svm.fit(X_train, y_train)

SVC(C=30, gamma='auto')

In [ ]:
model_svm.score(X_test, y_test)

0.98

# now using grid serach CV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear']
},cv=5,return_train_score=False)

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
print(classifier.cv_results_)

{'mean_fit_time': array([0.00580473, 0.00433183, 0.00470729, 0.00816326, 0.00502753,
       0.00517879, 0.00361085, 0.0043272 ]), 'std_fit_time': array([1.63213062e-03, 4.40480890e-04, 1.39270045e-03, 3.74002253e-03,
       1.40920455e-03, 1.55887346e-03, 8.99226891e-05, 1.72901536e-03]), 'mean_score_time': array([0.00522881, 0.00307593, 0.00357876, 0.00747442, 0.00483441,
       0.00479441, 0.00268598, 0.00368714]), 'std_score_time': array([3.36017093e-03, 4.59084409e-04, 1.88367530e-03, 2.93479801e-03,
       2.11588254e-03, 2.57591939e-03, 5.18765957e-05, 1.63229223e-03]), 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
             mask=[False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                   'rbf', 'linear'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 1, 'kernel': 'rbf'}, {'C': 1, 'kernel': 'linear'}, {'C': 10, 'kernel': 'rbf'}, {'C': 10, 'kernel': 'linear'}, {'C': 20, 'kernel': 'rbf'}, {'C': 20, 'kernel': 'linear'}, {'C': 30, 'kernel': 'rbf'}, {'C': 30, 'kernel': 'linear'}], 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
       1.        , 0.96666667, 1.        ]), 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]), 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
       0.9       , 0.9       , 0.9       ]), 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.93333333, 0.93333333, 0.9       ]), 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]), 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
       0.96666667, 0.96      , 0.96      ]), 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
       0.0421637 , 0.03887301, 0.04898979]), 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005805,0.001632,0.005229,0.003360,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004332,0.000440,0.003076,0.000459,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004707,0.001393,0.003579,0.001884,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.008163,0.003740,0.007474,0.002935,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.005028,0.001409,0.004834,0.002116,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.005179,0.001559,0.004794,0.002576,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003611,0.000090,0.002686,0.000052,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.004327,0.001729,0.003687,0.001632,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
classifier_1 = GridSearchCV(model_knn,{
    'n_neighbors' : [3,5,7,9,11],
    'weights' : ['uniform','distance'],
    'metric' : ['euclidean','manhattan']
},cv=5,return_train_score=False)

In [ ]:
classifier_1.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=25),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']})

In [ ]:
results_1 = pd.DataFrame(classifier_1.cv_results_)

In [ ]:
results_1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008276,0.004069,0.014155,0.005126,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,11
1,0.005459,0.001531,0.005565,0.002502,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,11
2,0.004756,0.001818,0.007077,0.001533,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
3,0.009169,0.002749,0.010560,0.003878,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,11
4,0.007568,0.007602,0.007011,0.002724,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
5,0.009477,0.004635,0.013810,0.005891,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
6,0.004964,0.002559,0.005772,0.001853,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
7,0.004376,0.001543,0.004019,0.000869,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
8,0.007658,0.002734,0.008394,0.003022,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,2
9,0.004134,0.001700,0.003889,0.000929,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
10,0.004495,0.001768,0.006978,0.003456,manhattan,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,19
11,0.004575,0.002377,0.003732,0.000925,manhattan,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,19
12,0.003170,0.000054,0.004509,0.000142,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
13,0.006597,0.003911,0.007599,0.004220,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
14,0.016459,0.006180,0.021661,0.005710,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
15,0.010865,0.004066,0.011389,0.002387,manhattan,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
16,0.004964,0.001522,0.006179,0.002023,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
17,0.008126,0.005212,0.006307,0.002693,manhattan,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
18,0.003734,0.000798,0.007144,0.005117,manhattan,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
19,0.003183,0.000078,0.003597,0.000231,manhattan,11,distance,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,11

In [ ]:
results_1[['param_n_neighbors','param_weights','param_metric','mean_test_score']]

    param_n_neighbors param_weights param_metric  mean_test_score
0                   3       uniform    euclidean         0.966667
1                   3      distance    euclidean         0.966667
2                   5       uniform    euclidean         0.973333
3                   5      distance    euclidean         0.966667
4                   7       uniform    euclidean         0.980000
5                   7      distance    euclidean         0.980000
6                   9       uniform    euclidean         0.973333
7                   9      distance    euclidean         0.973333
8                  11       uniform    euclidean         0.980000
9                  11      distance    euclidean         0.986667
10                  3       uniform    manhattan         0.960000
11                  3      distance    manhattan         0.960000
12                  5       uniform    manhattan         0.960000
13                  5      distance    manhattan         0.960000
14                  7       uniform    manhattan         0.973333
15                  7      distance    manhattan         0.960000
16                  9       uniform    manhattan         0.973333
17                  9      distance    manhattan         0.960000
18                 11       uniform    manhattan         0.980000
19                 11      distance    manhattan         0.966667

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear']
},n_iter=4 , cv=5,return_train_score=False)

In [ ]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
result_r = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
result_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004531,0.001104,0.003289,0.000524,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,3
1,0.006226,0.001624,0.003899,0.001559,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.009352,0.002335,0.006471,0.003203,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,3
3,0.005590,0.002704,0.003669,0.001821,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2

In [ ]:
result_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30       linear         0.960000
1       10          rbf         0.980000
2       30          rbf         0.960000
3       10       linear         0.973333

In [ ]:
classifier_r1 = RandomizedSearchCV(model_knn,{
    'n_neighbors' : [3,5,7,9,11],
    'weights' : ['uniform','distance'],
    'metric' : ['euclidean','manhattan']
},n_iter=5 , cv=5,return_train_score=False)

In [ ]:
classifier_r1.fit(X,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=25),
                   n_iter=5,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': [3, 5, 7, 9, 11],
                                        'weights': ['uniform', 'distance']})

In [ ]:
results_r1 = pd.DataFrame(classifier_r1.cv_results_)

In [ ]:
results_r1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_weights,param_n_neighbors,param_metric,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004299,0.000783,0.005665,0.000654,uniform,7,euclidean,"{'weights': 'uniform', 'n_neighbors': 7, 'metr...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004447,0.002339,0.005184,0.001557,distance,9,euclidean,"{'weights': 'distance', 'n_neighbors': 9, 'met...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,2
2,0.003852,0.000528,0.007326,0.003466,uniform,7,manhattan,"{'weights': 'uniform', 'n_neighbors': 7, 'metr...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,2
3,0.005943,0.003539,0.008337,0.004477,distance,3,euclidean,"{'weights': 'distance', 'n_neighbors': 3, 'met...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,5
4,0.007454,0.004085,0.009959,0.005921,uniform,9,euclidean,"{'weights': 'uniform', 'n_neighbors': 9, 'metr...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,2

In [ ]:
results_r1[['param_n_neighbors','param_weights','param_metric','mean_test_score']]

   param_n_neighbors param_weights param_metric  mean_test_score
0                  7       uniform    euclidean         0.980000
1                  9      distance    euclidean         0.973333
2                  7       uniform    manhattan         0.973333
3                  3      distance    euclidean         0.966667
4                  9       uniform    euclidean         0.973333